-- h2 db 버전
-- drop table if exists member CASCADE;
-- create table member
-- (
--     id   bigint generated by default as identity,
--     name varchar(255),
--     primary key (id)
-- );

-- MySQL 버전
drop table if exists member CASCADE;
create table member
(
    id   bigint AUTO_INCREMENT,
    name varchar(255),
    primary key (id)
);